// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etztlxlfgoqbgwyaozwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0enRseGxmZ29xYmd3eWFvendmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzE2NDAsImV4cCI6MjA2ODkwNzY0MH0.gGDCHoMv3J3La2h7QCItNS56Xs-UrhaNa6M_jFZ9w9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);