// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wphzuhmsttxsaauyhlib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwaHp1aG1zdHR4c2FhdXlobGliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4Nzg5OTUsImV4cCI6MjA1ODQ1NDk5NX0.VfU8ZCrVk3FYhmCLB4lRqU5xiGqLWPGMCA4E2IHlMs8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);